"""create shopping tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 18:37:22.907664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_products_owner_id_name')
    )
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_owner_id'), 'shopping_lists', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_share_token'), 'shopping_lists', ['share_token'], unique=True)
    op.create_index('uq_shopping_lists_owner_active', 'shopping_lists', ['owner_id'], unique=True, sqlite_where=sa.text('completed_at IS NULL'), postgresql_where=sa.text('completed_at IS NULL'))
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_shopping_list_items_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopping_list_id', 'product_id', name='uq_shopping_list_items_list_product')
    )
    op.create_index(op.f('ix_shopping_list_items_product_id'), 'shopping_list_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_product_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index('uq_shopping_lists_owner_active', table_name='shopping_lists', sqlite_where=sa.text('completed_at IS NULL'), postgresql_where=sa.text('completed_at IS NULL'))
    op.drop_index(op.f('ix_shopping_lists_share_token'), table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_owner_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
